[project]
name = "av4-sofielau"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sofi933", email = "sofiacostalaus2009@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=26.7.0",
]

[project.scripts]
av4-sofielau = "av4_sofielau:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
